# call to chat gpt for completion TODO: Could add  limits here?
def openai_gpt_chatcompletion(messages_dict_gpt=None,OPENAI_API_KEY=None): 
    """
    Send a message to OpenAI GPT-3.5-turbo for completion and get the response.

    Parameters:
    - messages_dict_gpt (dict): Dictionary containing the message structure for the GPT prompt.
    - OPENAI_API_KEY (str): API key to authenticate with OpenAI.

    Returns:
    str: The content of the message generated by GPT.
    """
    import openai

    #attach openai api key
    openai.api_key = OPENAI_API_KEY

    #request to openai
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        #model="gpt-4-turbo",
        messages=messages_dict_gpt
    )
    
    #review what's been provided by GPT
    gpt_response = completion.choices[0].message['content']
    print('---------- Prompt Message Dictionary')
    print(messages_dict_gpt)
    print("----------  GPT Response:")
    print(completion.choices[0].message)

    #send the gpt response as discord bot message
    return gpt_response